/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coworkify.Usuario.Vista;

/**
 *
 * @author Dani Beva
 */
public class inicio_sesion extends javax.swing.JFrame {

    /**
     * Creates new form inicio_sesion
     */
    public inicio_sesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ingresarcuenta = new javax.swing.JTextField();
        ingresarcontraseña = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButton1.setText("INICIAR SESION");
        jPanel1.add(jButton1);
        jButton1.setBounds(210, 270, 140, 40);

        jButton2.setText("CREAR UNA CUENTA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(190, 330, 180, 20);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("INGRESAR CUENTA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 60, 230, 40);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setText("INGRESAR CONTRASEÑA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 150, 310, 40);

        ingresarcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarcuentaActionPerformed(evt);
            }
        });
        jPanel1.add(ingresarcuenta);
        ingresarcuenta.setBounds(160, 100, 230, 40);

        ingresarcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarcontraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(ingresarcontraseña);
        ingresarcontraseña.setBounds(160, 200, 230, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 560, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ingresarcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarcuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarcuentaActionPerformed

    private void ingresarcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarcontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarcontraseñaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ingresarcontraseña;
    private javax.swing.JTextField ingresarcuenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
